# Generated by Django 4.2.9 on 2026-03-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testcases", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testplan_name", models.CharField(max_length=100)),
                (
                    "plandesc_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "plandesc_pmtid",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "plandesc_tested",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "plandesc_nottested",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "plandesc_references",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "plandesc_esttime",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("plan_active", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testplans",
                        to="projects.project",
                    ),
                ),
                (
                    "testcases",
                    models.ManyToManyField(
                        blank=True,
                        db_table="testplan_testcase",
                        related_name="testplans",
                        to="testcases.testcase",
                    ),
                ),
            ],
            options={
                "db_table": "testplans",
            },
        ),
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_version", models.CharField(max_length=100)),
                ("build_desc", models.CharField(blank=True, max_length=500, null=True)),
                ("build_active", models.BooleanField(default=True)),
                ("build_open", models.BooleanField(default=True)),
                ("build_releaseDate", models.DateField()),
                (
                    "testplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builds",
                        to="testplans.testplan",
                    ),
                ),
            ],
            options={
                "db_table": "builds",
            },
        ),
    ]
