# Generated by Django 4.2.9 on 2026-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("prefix", models.CharField(max_length=20, unique=True)),
                ("project_description", models.TextField(blank=True, default="")),
                ("enable_requirements", models.BooleanField(default=False)),
                ("enable_testing_priority", models.BooleanField(default=False)),
                ("enable_test_automation", models.BooleanField(default=False)),
                ("enable_inventory", models.BooleanField(default=False)),
                ("project_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "projects",
            },
        ),
    ]
