# Generated by Django 6.0.2 on 2026-03-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="taiga_project_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
