# Generated by Django 4.2.9 on 2026-03-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_taiga_project_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"managed": False},
        ),
    ]
