# Generated by Django 4.2.9 on 2026-03-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testplans", "0001_initial"),
        ("accounts", "0001_initial"),
        ("testcases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Not Run", max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "attachment_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testplans.build",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.user",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testcases.testcase",
                    ),
                ),
                (
                    "testplan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testplans.testplan",
                    ),
                ),
            ],
            options={
                "db_table": "test_executions",
            },
        ),
        migrations.CreateModel(
            name="TestExecutionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_no", models.IntegerField()),
                ("action", models.TextField(blank=True, null=True)),
                ("expected_result", models.TextField(blank=True, null=True)),
                ("actual_result", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("bug_id_ref", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_results",
                        to="executions.testexecution",
                    ),
                ),
            ],
            options={
                "db_table": "test_execution_steps",
                "ordering": ["step_no"],
            },
        ),
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bug_key", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="executions.testexecution",
                    ),
                ),
            ],
            options={
                "db_table": "bugs",
            },
        ),
    ]
