# Generated by Django 6.0.3 on 2026-03-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_issue_issues_issu_task_id_570486_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"managed": False},
        ),
    ]
