# Generated by Django 6.0.3 on 2026-03-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_mirror_issues_managed_false"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="issue",
            table="issues",
        ),
    ]
