# Generated by Django 4.2.9 on 2026-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("employee_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
                ("role", models.CharField(default="viewer", max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
