# Generated by Django 4.2.9 on 2026-03-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "keywords",
            },
        ),
        migrations.CreateModel(
            name="Suite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suite_name", models.CharField(max_length=200)),
                ("suite_description", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suites",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "suites",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=50, null=True)),
                ("testcase_name", models.CharField(max_length=300)),
                ("testcase_summary", models.TextField(blank=True, null=True)),
                ("testcase_precondition", models.TextField(blank=True, null=True)),
                ("testcase_status", models.CharField(default="Draft", max_length=50)),
                (
                    "testcase_importance",
                    models.CharField(default="Medium", max_length=50),
                ),
                (
                    "testcase_executiontype",
                    models.CharField(default="Manual", max_length=50),
                ),
                (
                    "testcase_type",
                    models.CharField(default="Functional", max_length=50),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True,
                        db_table="testcase_keyword_assoc",
                        related_name="testcases",
                        to="testcases.keyword",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="testcases.suite",
                    ),
                ),
            ],
            options={
                "db_table": "testcases",
            },
        ),
        migrations.CreateModel(
            name="TestSuiteLegacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suite_name", models.CharField(max_length=100)),
                (
                    "suite_detail",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testsuites_legacy",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "testsuites_legacy",
            },
        ),
        migrations.CreateModel(
            name="TestCaseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_no", models.IntegerField()),
                ("precondition", models.TextField(blank=True, null=True)),
                ("action", models.TextField()),
                ("expected_result", models.TextField()),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="testcases.testcase",
                    ),
                ),
            ],
            options={
                "db_table": "testcase_steps",
                "ordering": ["step_no"],
            },
        ),
    ]
