# Generated by Django 4.2.9 on 2026-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("BUG", "Bug"),
                    ("ENHANCEMENT", "Enhancement"),
                    ("TASK", "Task"),
                ],
                default="BUG",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Medium",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved / Ready for Test"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=50,
            ),
        ),
    ]
