# Generated by Django 6.0.2 on 2026-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enable_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_requirements",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_test_automation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_testing_priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="prefix",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="project_active",
            field=models.BooleanField(default=True),
        ),
    ]
