# Generated by Django 6.0.3 on 2026-03-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_project_enable_inventory_project_enable_requirements_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="project",
            table="projects",
        ),
    ]
